/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DynamicTable: typeof import('./src/components/DynamicTable.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FlexiTable: typeof import('./src/components/FlexiTable.vue')['default']
    PopupEditLabel: typeof import('./src/components/PopupEditLabel.vue')['default']
    TableEditor: typeof import('./src/components/TableEditor.vue')['default']
  }
}
