import { VfField, VfType } from '@/interfaces/table';

export const symbols: VfField[] = [
  {
    vfTitle: '⌴',
    vfCode: 'space',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'space',
    vfActualFieldTitle: 'Dấu cách',
    value: '&nbsp;',
  },
  {
    vfTitle: '↩',
    vfCode: 'newline',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'newline',
    vfActualFieldTitle: 'NewLine',
    value: '<br/>',
  },
  {
    vfTitle: '-',
    vfCode: 'minus',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'minus',
    vfActualFieldTitle: 'Dấu trừ',
    value: '&hyphen;',
  },
  {
    vfTitle: '_',
    vfCode: 'underscore',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'underscore',
    vfActualFieldTitle: 'Dấu gạch dưới',
    value: '_',
  },
  {
    vfTitle: '|',
    vfCode: 'vertical',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'vertical',
    vfActualFieldTitle: 'Dấu dọc',
    value: '|',
  },
  {
    vfTitle: ',',
    vfCode: 'comma',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'comma',
    vfActualFieldTitle: 'Dấu phẩy',
    value: ',',
  },
  {
    vfTitle: ':',
    vfCode: 'colon',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'colon',
    vfActualFieldTitle: 'Hai chấm',
    value: ':',
  },
  {
    vfTitle: '.',
    vfCode: 'dot',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'dot',
    vfActualFieldTitle: 'Dấu chấm',
    value: '.',
  },
  {
    vfTitle: ';',
    vfCode: 'semicolon',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'semicolon',
    vfActualFieldTitle: 'Chấm phẩy',
    value: ';',
  },
  {
    vfTitle: '/',
    vfCode: 'slash',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'slash',
    vfActualFieldTitle: 'Dấu gạch chéo',
    value: '/',
  },
  {
    vfTitle: '\\',
    vfCode: 'backslash',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'backslash',
    vfActualFieldTitle: 'Dấu gạch chéo ngược',
    value: '\\',
  },
  {
    vfTitle: '?',
    vfCode: 'question',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'question',
    vfActualFieldTitle: 'Dấu hỏi',
    value: '?',
  },
  {
    vfTitle: '~',
    vfCode: 'tilde',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'tilde',
    vfActualFieldTitle: 'Dấu ngã',
    value: '~',
  },
  {
    vfTitle: '@',
    vfCode: 'at',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'at',
    vfActualFieldTitle: 'Dấu @',
    value: '@',
  },
  {
    vfTitle: '#',
    vfCode: 'hash',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'hash',
    vfActualFieldTitle: 'Dấu #',
    value: '#',
  },
  {
    vfTitle: '$',
    vfCode: 'dollar',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'dollar',
    vfActualFieldTitle: 'Dấu $',
    value: '$',
  },
  {
    vfTitle: '^',
    vfCode: 'caret',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'caret',
    vfActualFieldTitle: 'Dấu mũ',
    value: '^',
  },
  {
    vfTitle: '&',
    vfCode: 'ampersand',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'ampersand',
    vfActualFieldTitle: 'Dấu &',
    value: '&',
  },
  {
    vfTitle: '*',
    vfCode: 'asterisk',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'asterisk',
    vfActualFieldTitle: 'Dấu *',
    value: '*',
  },
  {
    vfTitle: '[',
    vfCode: 'openBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'openBracket',
    vfActualFieldTitle: 'Mở ngoặc vuông',
    value: '[',
  },
  {
    vfTitle: ']',
    vfCode: 'closeBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'closeBracket',
    vfActualFieldTitle: 'Đóng ngoặc vuông',
    value: ']',
  },
  {
    vfTitle: '(',
    vfCode: 'openRoundBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'openRoundBracket',
    vfActualFieldTitle: 'Mở ngoặc tròn',
    value: '(',
  },
  {
    vfTitle: ')',
    vfCode: 'closeRoundBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'closeRoundBracket',
    vfActualFieldTitle: 'Đóng hoặc tròn',
    value: ')',
  },
  {
    vfTitle: '<',
    vfCode: 'openAngleBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'openAngleBracket',
    vfActualFieldTitle: 'Mở ngoặc nhọn',
    value: '&lt;',
  },
  {
    vfTitle: '>',
    vfCode: 'closeAngleBracket',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'closeAngleBracket',
    vfActualFieldTitle: 'Đóng ngoặc nhọn',
    value: '&gt;',
  },
  {
    vfTitle: '"',
    vfCode: 'doubleQuote',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'doubleQuote',
    vfActualFieldTitle: 'Dấu ngoặc kép',
    value: '"',
  },
  {
    vfTitle: "'",
    vfCode: 'singleQuote',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'singleQuote',
    vfActualFieldTitle: 'Dấu ngoặc đơn',
    value: "'",
  },
  {
    vfTitle: '`',
    vfCode: 'backtick',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'backtick',
    vfActualFieldTitle: 'Dấu ngoặc ngược',
    value: '`',
  },
  {
    vfTitle: '€',
    vfCode: 'euro',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'euro',
    vfActualFieldTitle: 'Euro',
    value: '€',
  },
  {
    vfTitle: '£',
    vfCode: 'pound',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'pound',
    vfActualFieldTitle: 'Pound',
    value: '£',
  },
  {
    vfTitle: '¥',
    vfCode: 'yen',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'yen',
    vfActualFieldTitle: 'Yen',
    value: '¥',
  },
  {
    vfTitle: '¢',
    vfCode: 'cent',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'cent',
    vfActualFieldTitle: 'Cent',
    value: '¢',
  },
  {
    vfTitle: '©',
    vfCode: 'copyright',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'copyright',
    vfActualFieldTitle: 'Copyright',
    value: '©',
  },
  {
    vfTitle: '®',
    vfCode: 'registered',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'registered',
    vfActualFieldTitle: 'Registered',
    value: '®',
  },
  {
    vfTitle: '™',
    vfCode: 'trademark',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'trademark',
    vfActualFieldTitle: 'Trademark',
    value: '™',
  },
  {
    vfTitle: '§',
    vfCode: 'section',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'section',
    vfActualFieldTitle: 'Section',
    value: '§',
  },
  {
    vfTitle: '¶',
    vfCode: 'paragraph',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'paragraph',
    vfActualFieldTitle: 'Paragraph',
    value: '¶',
  },
  {
    vfTitle: '°',
    vfCode: 'degree',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'degree',
    vfActualFieldTitle: 'Degree',
    value: '°',
  },
  {
    vfTitle: '±',
    vfCode: 'plusMinus',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'plusMinus',
    vfActualFieldTitle: 'Plus Minus',
    value: '±',
  },
  {
    vfTitle: '×',
    vfCode: 'multiply',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'multiply',
    vfActualFieldTitle: 'Multiply',
    value: '×',
  },
  {
    vfTitle: '÷',
    vfCode: 'divide',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'divide',
    vfActualFieldTitle: 'Divide',
    value: '÷',
  },
  {
    vfTitle: '≠',
    vfCode: 'notEqual',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'notEqual',
    vfActualFieldTitle: 'Not Equal',
    value: '≠',
  },
  {
    vfTitle: '≤',
    vfCode: 'lessThanOrEqual',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'lessThanOrEqual',
    vfActualFieldTitle: 'Less Than Or Equal',
    value: '≤',
  },
  {
    vfTitle: '≥',
    vfCode: 'greaterThanOrEqual',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'greaterThanOrEqual',
    vfActualFieldTitle: 'Greater Than Or Equal',
    value: '≥',
  },
  {
    vfTitle: '≈',
    vfCode: 'approximatelyEqual',
    vfType: VfType.SYMBOL,
    vfAcutalField: 'approximatelyEqual',
    vfActualFieldTitle: 'Approximately Equal',
    value: '≈',
  }
];

export const actions: VfField[] = [
  {
    vfTitle: 'Detail',
    vfCode: 'detail',
    vfType: VfType.ACTION,
    vfAcutalField: 'detail',
    vfActualFieldTitle: 'Detail',
    value: 'Detail',
  },
  {
    vfTitle: 'Update',
    vfCode: 'update',
    vfType: VfType.ACTION,
    vfAcutalField: 'update',
    vfActualFieldTitle: 'update',
    value: 'Update',
  },
  {
    vfTitle: 'Delete',
    vfCode: 'delete',
    vfType: VfType.ACTION,
    vfAcutalField: 'delete',
    vfActualFieldTitle: 'delete',
    value: 'Delete',
  },
];